### ISSUE TITLE
Post-processing failing to move file

### ISSUE THREAD

**Issue by skywayskase** [nosmokingbandit/Watcher3#70] opened 2017-06-17 09:57 UTC
I'm running Ubuntu 17.04 and trying to move the files to Google drive using a FUSE based filesystem (https://github.com/astrada/google-drive-ocamlfuse).
I can manually move the file to this mount, and while it'll take a while, it will successfully move the file into Google Drive, but when I try to have Watcher3 move it as part of post-processing, it fails.

```
DEBUG 2017-06-17 02:22:20,342 core.postprocessing.POST: {'mode': 'complete', 'downloadid': '105', 'apikey': '*REMOVED*', 'path': '/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES', 'guid': 'https://api.nzbgeek.info/api?t=get&id=*REMOVED*'}
INFO 2017-06-17 02:22:20,342 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-06-17 02:22:20,342 core.postprocessing.get_movie_file: Post-processing file /home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv.
INFO 2017-06-17 02:22:20,342 core.postprocessing.POST: Gathering release information.
INFO 2017-06-17 02:22:20,343 core.postprocessing.get_movie_info: Searching local database for guid.
DEBUG 2017-06-17 02:22:20,343 core.sqldb.get_single_search_result: Retrieving search result details for https://api.nzbgeek.info/api?t=get.
INFO 2017-06-17 02:22:20,343 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-06-17 02:22:20,344 core.postprocessing.get_movie_info: Searching local database by imdbid.
DEBUG 2017-06-17 02:22:20,344 core.sqldb.get_movie_details: Retrieving details for tt1412528.
INFO 2017-06-17 02:22:20,344 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-06-17 02:22:20,344 core.library.from_file: Gathering metadata for /home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv.
INFO 2017-06-17 02:22:20,344 core.library.parse_filename: Parsing /home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv for movie information.
INFO 2017-06-17 02:22:20,345 core.library.parse_filename: Parsing filename doesn't look accurate. Parsing parent folder name.
INFO 2017-06-17 02:22:20,345 core.library.parse_filename: Found {'quality': 'BluRay', 'resolution': '720p', 'codec': 'x264', 'year': 2017, 'group': 'DRONES', 'title': 'Table 19'} in parent folder.
INFO 2017-06-17 02:22:20,351 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?page=1&include_adult=false&query=table+19&year=2017
INFO 2017-06-17 02:22:20,927 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-06-17 02:22:20,927 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-06-17 02:22:20,927 core.library.searchresults: Marking guid https://api.nzbgeek.info/api?t=get as Finished.
INFO 2017-06-17 02:22:20,928 core.library.searchresults: Marking https://api.nzbgeek.info/api?t=get as Finished in SEARCHRESULTS.
DEBUG 2017-06-17 02:22:20,928 core.sqldb.update: Updating status to Finished for col guid:https://api.nzbgeek.info/api?t=get in SEARCHRESULTS.
INFO 2017-06-17 02:22:20,933 core.library.searchresults: Successfully marked https://api.nzbgeek.info/api?t=get as Finished in SEARCHRESULTS.
INFO 2017-06-17 02:22:20,934 core.library.markedresults: Marking https://api.nzbgeek.info/api?t=get as Finished in MARKEDRESULTS.
DEBUG 2017-06-17 02:22:20,934 core.sqldb.update: Updating status to Finished for col guid:https://api.nzbgeek.info/api?t=get in MARKEDRESULTS.
INFO 2017-06-17 02:22:20,938 core.library.markedresults: Successfully marked https://api.nzbgeek.info/api?t=get as Finished in MARKEDRESULTS.
INFO 2017-06-17 02:22:20,939 core.postprocessing.complete: Setting MOVIE status.
DEBUG 2017-06-17 02:22:20,939 core.sqldb.get_movie_details: Retrieving details for tt1412528.
DEBUG 2017-06-17 02:22:20,940 core.sqldb.get_distinct: Getting distinct values for tt1412528 in SEARCHRESULTS
INFO 2017-06-17 02:22:20,940 core.library.movie_status: Setting MOVIES tt1412528 status to Finished.
DEBUG 2017-06-17 02:22:20,940 core.sqldb.update: Updating status to Finished for col imdbid:tt1412528 in MOVIES.
DEBUG 2017-06-17 02:22:20,944 core.sqldb.update_multiple: Updating tt1412528 to {'finished_score': 620, 'finished_date': '2017-06-17'} in MOVIES.
DEBUG 2017-06-17 02:22:20,949 core.postprocessing.compile_path: Created path Table 19 from {title}
INFO 2017-06-17 02:22:20,949 core.postprocessing.renamer: Renaming Table 19.mkv to Table 19.mkv
DEBUG 2017-06-17 02:22:20,949 core.postprocessing.compile_path: Created path  from 
DEBUG 2017-06-17 02:22:20,949 core.postprocessing.compile_path: Created path /home/skywayskase/googledrive/Media/Movies/Table 19 (2017) from /home/skywayskase/googledrive/Media/Movies/{title} ({year})
INFO 2017-06-17 02:22:21,344 core.postprocessing.mover: Moving /home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv to /home/skywayskase/googledrive/Media/Movies/Table 19 (2017)/
ERROR 2017-06-17 02:34:01,814 core.postprocessing.mover: Mover failed: Could not move file.
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv' -> '/home/skywayskase/googledrive/Media/Movies/Table 19 (2017)/Table 19.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python3.5/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
ConnectionAbortedError: [Errno 103] Software caused connection abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/watcher3/core/postprocessing.py", line 688, in mover
    shutil.move(current_file_path, target_folder)
  File "/usr/lib/python3.5/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.5/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 107] Transport endpoint is not connected
DEBUG 2017-06-17 02:34:01,989 core.sqldb.update: Updating finished_file to None for col imdbid:tt1412528 in MOVIES.
INFO 2017-06-17 02:34:01,998 core.postprocessing.complete: Mover either disabled or failed. Skipping Cleanup.
INFO 2017-06-17 02:34:01,999 core.postprocessing.POST: {'tasks': {'https://api.nzbgeek.info/api?t=get&id=*REMOVED*': {'update_MARKEDRESULTS': True, 'update_SEARCHRESULTS': True}, 'renamer': {'response': True, 'enabled': True}, 'update_movie_status': 'Finished', 'cleanup': {'response': False, 'enabled': True}, 'mover': {'response': False, 'enabled': True}}, 'status': 'finished', 'data': {'downloadid': '105', 'releasegroup': 'DRONES', 'release_date': '2017-01-20', 'overview': 'Eloise, having been relieved of maid of honor duties after being unceremoniously dumped by the best man via text, decides to attend the wedding anyway, only to find herself seated with five fellow unwanted guests at the dreaded Table 19.', 'finished_date': '2017-06-17', 'poster_path': '/vz0CWnSwcQz1si7pLZp4hC4A1zi.jpg', 'digital_release_date': '2017-05-31', 'movie_file': '/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv', 'vote_average': 6.2, 'added_date': '2017-06-17', 'mode': 'complete', 'apikey': '*REMOVED*', 'rated': None, 'predb_backlog': '1', 'videocodec': 'MPEG4', 'path': '/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES', 'guid': 'https://api.nzbgeek.info/api?t=get&id=*REMOVED*', 'id': 353569, 'video': False, 'original_language': 'en', 'year': '2017', 'title': 'Table 19', 'audiocodec': 'DTS', 'finished_score': 620, 'imdbid': 'tt1412528', 'tmdbid': '353569', 'adult': False, 'alternative_titles': '', 'url': 'https://www.themoviedb.org/movie/353569', 'original_title': 'Table 19', 'status': 'Finished', 'quality': 'Default', 'origin': 'Search', 'original_file': '/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv', 'resolution': 'BluRay-720P', 'genre_ids': [35, 18], 'vote_count': 70, 'plot': 'Eloise, having been relieved of maid of honor duties after being unceremoniously dumped by the best man via text, decides to attend the wedding anyway, only to find herself seated with five fellow unwanted guests at the dreaded Table 19.', 'finished_file': None, 'poster': 'images/poster/tt1412528.jpg', 'popularity': 5.310743, 'backdrop_path': '/c7kC6TKTZkQSOh2YINgmbVk2N35.jpg', 'score': '6.2'}}
INFO 2017-06-17 02:34:01,999 core.postprocessing.POST: #################################
INFO 2017-06-17 02:34:01,999 core.postprocessing.POST: Post-processing complete.
INFO 2017-06-17 02:34:01,999 core.postprocessing.POST: {
  "data": {
    "added_date": "2017-06-17",
    "adult": false,
    "alternative_titles": "",
    "apikey": "*REMOVED*",
    "audiocodec": "DTS",
    "backdrop_path": "/c7kC6TKTZkQSOh2YINgmbVk2N35.jpg",
    "digital_release_date": "2017-05-31",
    "downloadid": "105",
    "finished_date": "2017-06-17",
    "finished_file": null,
    "finished_score": 620,
    "genre_ids": [
      35,
      18
    ],
    "guid": "https://api.nzbgeek.info/api?t=get&id=*REMOVED*",
    "id": 353569,
    "imdbid": "tt1412528",
    "mode": "complete",
    "movie_file": "/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv",
    "origin": "Search",
    "original_file": "/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES/Table 19.mkv",
    "original_language": "en",
    "original_title": "Table 19",
    "overview": "Eloise, having been relieved of maid of honor duties after being unceremoniously dumped by the best man via text, decides to attend the wedding anyway, only to find herself seated with five fellow unwanted guests at the dreaded Table 19.",
    "path": "/home/skywayskase/downloads/completed/movies/Table.19.2017.720p.BluRay.x264-DRONES",
    "plot": "Eloise, having been relieved of maid of honor duties after being unceremoniously dumped by the best man via text, decides to attend the wedding anyway, only to find herself seated with five fellow unwanted guests at the dreaded Table 19.",
    "popularity": 5.310743,
    "poster": "images/poster/tt1412528.jpg",
    "poster_path": "/vz0CWnSwcQz1si7pLZp4hC4A1zi.jpg",
    "predb_backlog": "1",
    "quality": "Default",
    "rated": null,
    "release_date": "2017-01-20",
    "releasegroup": "DRONES",
    "resolution": "BluRay-720P",
    "score": "6.2",
    "status": "Finished",
    "title": "Table 19",
    "tmdbid": "353569",
    "url": "https://www.themoviedb.org/movie/353569",
    "video": false,
    "videocodec": "MPEG4",
    "vote_average": 6.2,
    "vote_count": 70,
    "year": "2017"
  },
  "status": "finished",
  "tasks": {
    "cleanup": {
      "enabled": true,
      "response": false
    },
    "https://api.nzbgeek.info/api?t=get&id=*REMOVED*": {
      "update_MARKEDRESULTS": true,
      "update_SEARCHRESULTS": true
    },
    "mover": {
      "enabled": true,
      "response": false
    },
    "renamer": {
      "enabled": true,
      "response": true
    },
    "update_movie_status": "Finished"
  }
}
INFO 2017-06-17 02:34:01,999 core.postprocessing.POST: #################################
```

**Comment by nosmokingbandit** [comment] 2017-06-25 01:27
So for whatever reason I didn't get an email alerting me to this issue. I didn't mean to ignore you.

It looks like you have hardlinks enabled, is this correct? Hardlinks do not work across filesystems or partitions, which could be the cause of the exception.

**Comment by skywayskase** [comment] 2017-06-26 12:54
Actually, I don't have hardlinks enabled, although I do see the error about cross-device links. Since I'm not torrenting, and I have limited space on my local drive, I just want to move the files off my local machine and onto the remote mount, so hardlinking is not checked in the UI.

**Comment by nosmokingbandit** [comment] 2017-06-26 17:27
That might have something to do with the way the drive is mounted. The OS seems to think it is actually a local directory rather than a mounted network drive.

google-drive-ocamlfuse doesn't want to work on my virtual-machine, so once I get that figured out I'll be able to see exactly what is going on.

**Comment by nosmokingbandit** [comment] 2017-06-27 01:17
What version of Python are you running? Shutil is has a fallback for this but for whatever reason isn't working in your case.

**Comment by skywayskase** [comment] 2017-06-27 12:16
```
skywayskase@mdm1:~$ python --version
Python 2.7.13
skywayskase@mdm1:~$ python3 --version
Python 3.5.3
```

**Comment by nosmokingbandit** [comment] 2017-06-27 19:22
Has this happened repeatedly? I've tested all of the commands individually
and it works fine in my virtual machine.

I can write my own fallback method for it, but if it was just a once-off
bug in the google drive protocol I'd rather not.

**Comment by nosmokingbandit** [comment] 2017-08-03 20:15
Closing due to age. If this still needs attention feel free to post again.

**Closed by nosmokingbandit** 2017-08-03 20:15 UTC
