### ISSUE TITLE
nzbget post-process not working

### ISSUE THREAD

**Issue by domenicdistefano** [nosmokingbandit/Watcher3#28] opened 2017-04-24 16:31 UTC
Noticed nzbget post-processing wasn't working anymore after updating to latest versions of everything.   See output below when trying to run test.py from the command  prompt.

-------------------------------------------------------------------------

C:\Watcher3\post scripts>c:\Python36-32\python.exe test.py
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    import urllib.parse.urlencode as urlencode
ModuleNotFoundError: No module named 'urllib.parse.urlencode'; 'urllib.parse' is not a package

C:\Watcher3\post scripts>c:\Python36-32\python.exe test2.py
Traceback (most recent call last):
  File "test2.py", line 23, in <module>
    import urllib.parse.urlencode as urlencode
ModuleNotFoundError: No module named 'urllib.parse.urlencode'; 'urllib.parse' is not a package

C:\Watcher3\post scripts>

**Comment by nosmokingbandit** [comment] 2017-04-24 20:27
Duplicate of #27.

**Closed by nosmokingbandit** 2017-04-24 20:27 UTC
