### ISSUE TITLE
search results saved in db with bad imdbid

### ISSUE THREAD

**Issue by deadc0de6** [nosmokingbandit/Watcher3#236] opened 2018-04-01 20:23 UTC
First thanks a lot for Watcher3, awesome project !

I recently noticed that some of the media I was expecting hadn't any results in the webif although the logs showed `Keeping X results.` (where X is not 0).

I digged a bit and noticed that some `imdbid` fields in the `SEARCHRESULTS` table of the db weren't prepended with the **tt**. I fixed those with a script what solved the issue (webif finally showed the expected results). 

I don't really know where those bad *imdbid* came from but it might be the source of other issues (#232, #218).

**Comment by deadc0de6** [comment] 2018-04-01 20:42
if it can help anyone, here's the script (this is dirty but it does its job).
Watcher should probably be shutdown before running it.
```python
#!/usr/bin/env python3
# author: deadc0de6

import sys
import os
import sqlite3

QUERY = 'select size, imdbid from SEARCHRESULTS where imdbid not like \'tt%\''
CHANGE = 'update SEARCHRESULTS set imdbid = \'tt{}\' where size = {} and imdbid like \'{}\''

usage = '{} <db-path>'.format(sys.argv[0])
if len(sys.argv) < 2:
    print(usage)
    sys.exit(1)

path = sys.argv[1]
if not os.path.exists(path):
    print('db \"{}\" does not exist'.format(path))
    sys.exit(1)

conn = sqlite3.connect(path)
c = conn.cursor()

# check the bad entries
print('getting the bad entries if any ...')
tochange=[]
for row in c.execute(QUERY):
    tochange.append(row)

print('found {} bad entries'.format(len(tochange)))
if len(tochange) > 0:
    text = input("continue [y|N] ?")
    if text != 'y':
        print('aborted')
        sys.exit(0)
    # then update
    print('fixing bad entries')
    for ch in tochange:
        size, imdbid = ch
        sql = CHANGE.format(imdbid, size, imdbid)
        c.execute(sql)

    print('commit changes to db')
    conn.commit()
    conn.close()

print('done')
sys.exit(0)
```

**Comment by nosmokingbandit** [comment] 2018-04-01 23:45
4b0eb71af9278dd8729ab2a0cdac2b38a5a8bec6

Fixed initial problem and includes a database update that iterates through all `SEARCHRESULTS` and fixes imdbid.

**Comment by deadc0de6** [comment] 2018-04-02 12:29
awesome thanks, sent you an email to discuss your *list of things*.

**Comment by LeeThompson** [comment] 2018-04-02 17:36
This commit doesn't work.  

If imdbid does not have the tt prefix, Python will see i['imdbid'] as a numeric, not a str, and then .startswith will fail.

Corrected (core/sqldb):

```
        for ind, i in enumerate(d):
            print('{}%\r'.format(int((ind + 1) / l * 100)), end='')
            t = str(i['imdbid'])
            if not t.startswith('tt'):
                n = 'tt' + t
                values.append({'imdbid': n, 'guid': i['guid']})
```

**Comment by deadc0de6** [comment] 2018-04-02 18:08
@LeeThompson based on your comment under https://github.com/nosmokingbandit/Watcher3/commit/4b0eb71af9278dd8729ab2a0cdac2b38a5a8bec6#commitcomment-28372974, it fails because there is no entry *imdbid* in one (or multiple) row in the *SEARCHRESULTS* table of the db and not because of numeric vs str (since `str(i['imdbid'])` will ensure it is indeed a str).

The problem lies somewhere else. That PR should fix it: https://github.com/nosmokingbandit/Watcher3/pull/238 however I'm not sure why you have rows without an *imdbid* in the first place.

**Comment by LeeThompson** [comment] 2018-04-02 19:12
Well the code I posted, works.  

The code in the commit (`4b0eb71af9278dd8729ab2a0cdac2b38a5a8bec6`) does **not** have the str prefix:

```
+        for ind, i in enumerate(d):
+            print('{}%\r'.format(int((ind + 1) / l * 100)), end='')
+            if not i['imdbid'].startswith('tt'):
+                n = 'tt' + i['imdbid']
+                values.append({'imdbid': n, 'guid': i['guid']})
+
```

**Comment by deadc0de6** [comment] 2018-04-02 20:10
should be fixed by https://github.com/nosmokingbandit/Watcher3/pull/238

**Comment by nosmokingbandit** [comment] 2018-04-03 01:48
Actually fixed with https://github.com/nosmokingbandit/Watcher3/commit/fd8279568095ce875fa4f3e5cec67e917f1bcd72

To make sure everyone is on the same page, the database cannot have `smallint`s and `string`s in the same column. Sqlite is fairly type-safe. But it is qualified with "fairly" because apparently a null value in the database cell will get returned as `None` by SQLAlchemy, which I didn't expect to see. I assumed without even a thought about it that an empty `string` cell in the database would be read as an empty string ie '``', but I was mistaken.

So the fix is to check `i['imdid']`'s truthiness since `None` is `False` when cast to boolean. Only if `i['imdbid']` contains a truthy value will it check `startswith()` since the only possible truthy values are populated strings.

I'm still a little concerned that an empty string cell is being read as None, and I might have to comb through the code and see if there are other instances where this can occur, but knowing the problem is 90% of fixing it.

**Closed** 2019-05-21 18:37 UTC
