### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by brinkdogg** [nosmokingbandit/Watcher3#269] opened 2018-08-10 21:28 UTC
Thanks for any help / ideas

* Enable debug logging in settings/server.

* Repeat the actions required to reproduce the error.
Happens every time I search for a movie repeats every time on the status page popup then search icon

Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: 
** Operating System: Ubuntu 16.04
** Python Version [python -V]: 3.5.2
** What happened: When searching for a release I receive error 500 Internal Server Error
** Logs:

**Comment by brinkdogg** [comment] 2018-08-10 21:29
[log.txt](https://github.com/nosmokingbandit/Watcher3/files/2279517/log.txt)

**Comment by brinkdogg** [comment] 2018-08-10 21:39
Also can verify an indexer - click the green computer button and nothing happens..

**Comment by JustARandomGuyHere** [comment] 2018-08-10 22:47
same since last update

**Comment by xGBHxPegasus** [comment] 2018-08-11 17:13
Most likely related but when the movie searcher runs you get the below in the logs:

WARNING [2018-08-11 18:10:39,431] CPTaskScheduler._task.266: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "C:\Watcher\Watcher3\lib\cherrypyscheduler.py", line 264, in _task
    self.task()
  File "C:\Watcher\Watcher3\core\searcher.py", line 90, in search_all
    rss_sync(rss_movies)
  File "C:\Watcher\Watcher3\core\searcher.py", line 241, in rss_sync
    scored_results = searchresults.score(new_results, imdbid=imdbid)
  File "C:\Watcher\Watcher3\core\searchresults.py", line 54, in score
    quality_profile = movie_details['quality']
UnboundLocalError: local variable 'movie_details' referenced before assignment
INFO [2018-08-11 18:10:39,446] CPTaskScheduler._task.273: == Finished Task: Movie Search ==

**Comment by brinkdogg** [comment] 2018-08-12 03:33
So how do I fix it?

**Comment by JustARandomGuyHere** [comment] 2018-08-12 09:03
Wait for an update and/or downgrade to previous release 👍

**Comment by nosmokingbandit** [comment] 2018-08-13 03:17
I saw #270 before I saw this and they are caused by the same error. I'll close this and move discussion to #270.

Should be fixed in https://github.com/nosmokingbandit/Watcher3/commit/4d9764881baddda454f6ffa774ebacad6c85b6ef

**Closed by nosmokingbandit** 2018-08-13 03:17 UTC
