### ISSUE TITLE
Cannot Import Name 'ajax'

### ISSUE THREAD

**Issue by DanGarion** [nosmokingbandit/Watcher3#43] opened 2017-05-08 21:41 UTC
Hello, I just installed clean from GIT and I'm getting the following error when I try to start Watcher3.

> pi@raspberrypi:/opt $ sudo python3 Watcher3/watcher.py
> /opt/Watcher3/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
>   warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> Traceback (most recent call last):
>   File "Watcher3/watcher.py", line 22, in <module>
>     from core import api, config, postprocessing, scheduler, sqldb
>   File "/opt/Watcher3/core/api.py", line 5, in <module>
>     from core import ajax, sqldb
>   File "/opt/Watcher3/core/ajax.py", line 9, in <module>
>     from core import config, library, plugins, searchresults, searcher, snatcher, sqldb, version
>   File "/opt/Watcher3/core/config.py", line 6, in <module>
>     from core import scheduler
>   File "/opt/Watcher3/core/scheduler.py", line 9, in <module>
>     from core.rss import imdb, popularmovies
>   File "/opt/Watcher3/core/rss/imdb.py", line 2, in <module>
>     from core import ajax, sqldb
> ImportError: cannot import name 'ajax'

Unsure what is going on as I know the file is there in core...

**Comment by nosmokingbandit** [comment] 2017-05-09 02:24
Everything is working well on my servers using https://github.com/nosmokingbandit/Watcher3/commit/6ade04d4e592d72dda00c1abebab7dd61e6fe19f. Try cloning again and see if anything changes.

**Comment by bundyboss** [comment] 2017-05-09 06:43
Same for me this morning after a new clone!

**Comment by DanGarion** [comment] 2017-05-09 14:21
I rmd the folder and started over. Still the same issue.

**Comment by toogaz** [comment] 2017-05-10 09:18
I've the same problem with me watcher update this week-end

**Comment by theflu** [comment] 2017-05-10 13:01
I reverted to a old commit to get it working, until it has been fixed.
```
git checkout cc5b4fd5c3f27bf9ee65942ba261db2bb8aa8e4c
```

**Comment by bundyboss** [comment] 2017-05-11 10:32
Thks theflu. I confirm that now it's working with this old version. I'm waiting for the next update.

**Comment by toogaz** [comment] 2017-05-11 11:21
i've disable the auto-update waiting for your new version

**Comment by BillVeusees** [comment] 2017-05-11 16:17
Same here on fresh install 
`git checkout cc5b4fd5c3f27bf9ee65942ba261db2bb8aa8e4c`
works around

**Comment by nosmokingbandit** [comment] 2017-05-12 15:59
Duplicate of https://github.com/nosmokingbandit/Watcher3/issues/42

**Closed by nosmokingbandit** 2017-05-12 15:59 UTC
