### ISSUE TITLE
ImportError: No module named 'pysqlite2'

### ISSUE THREAD

**Issue by tproenca** [nosmokingbandit/Watcher3#48] opened 2017-05-20 09:45 UTC
I'm trying to run on my Ubuntu 14.04. I cloned the project with git and try to execute like:

```
#: python3 watcher.py
```

but I'm the following exception
```
# python3 watcher.py 
/opt/watcher/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Opening SQL DB.
Traceback (most recent call last):
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.4/lib-dynload/_sqlite3.cpython-34m-arm-linux-gnueabihf.so: undefined symbol: sqlite3_transfer_bindings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/watcher/core/sqldb.py", line 23, in __init__
    self.engine = create_engine(DB_NAME, echo=False, connect_args={'timeout': 30})
  File "/opt/watcher/lib/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/watcher/lib/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'
Traceback (most recent call last):
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.4/lib-dynload/_sqlite3.cpython-34m-arm-linux-gnueabihf.so: undefined symbol: sqlite3_transfer_bindings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 22, in <module>
    from core import api, config, postprocessing, scheduler, sqldb
  File "/opt/watcher/core/api.py", line 5, in <module>
    from core import ajax, sqldb
  File "/opt/watcher/core/ajax.py", line 9, in <module>
    from core import config, library, plugins, searchresults, searcher, snatcher, sqldb, version
  File "/opt/watcher/core/config.py", line 6, in <module>
    from core import scheduler
  File "/opt/watcher/core/scheduler.py", line 8, in <module>
    from core import searcher, version
  File "/opt/watcher/core/searcher.py", line 5, in <module>
    from core import library, searchresults, snatcher, sqldb, proxy
  File "/opt/watcher/core/library.py", line 20, in <module>
    sql = sqldb.SQL()
  File "/opt/watcher/core/sqldb.py", line 23, in __init__
    self.engine = create_engine(DB_NAME, echo=False, connect_args={'timeout': 30})
  File "/opt/watcher/lib/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/watcher/lib/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
  File "/opt/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'
```

**Comment by andrewdens** [comment] 2017-06-05 05:47
Have you tried running as sudo? You might not have permission on the script. I see you logged another issue, if you figured out the solution feel free to close the issue

**Comment by nosmokingbandit** [comment] 2017-06-07 18:06
The root cause of this is sqlalchemy attempting to import sqlite3 and if that fails it attempts to load pysqlite2 (this gives sqlalchemy the ability to work with both python 2 and 3).

sqlite3 is part of the standard library for python3, so it seems that whatever build Ubuntu is using removed that package for whatever reason. You should be able to correct this by running `pip install sqlite3`

**Closed** 2017-07-29 18:56 UTC
