### ISSUE TITLE
Error Checking for Updates Current local hash not in git history.

### ISSUE THREAD

**Issue by whispy** [nosmokingbandit/Watcher3#169] opened 2017-12-06 23:57 UTC
I'm getting this error when checking for updates via the UI. I'm running Watcher in a Docker container.

Please let me know if you need any more information.

EDIT:

Here is the relevant log:
```
INFO 2017-12-06 18:43:39,406 CPTaskScheduler._task: == Finished Scheduled Task: Update Checker ==
DEBUG 2017-12-06 18:43:39,089 core.sqldb.execute: Executing SQL command: ['UPDATE TASKS SET last_execution=? WHERE name=?', ('2017-12-06 18:43:35', 'Update Checker')]
DEBUG 2017-12-06 18:43:39,089 core.sqldb.update: Updating last_execution to 2017-12-06 18:43:35 for rows that match name:Update Checker in TASKS.
DEBUG 2017-12-06 18:43:39,063 core.sqldb.execute: Executing SQL command: ['SELECT 1 FROM TASKS WHERE name="Update Checker"']
DEBUG 2017-12-06 18:43:39,063 core.sqldb.row_exists: Checking if name="Update Checker" exists in database table TASKS
DEBUG 2017-12-06 18:43:39,062 core.notification.add: {'message': 'Error Checking for Updates <br/> Current local hash not in git history.', 'timeout': 0, 'for': None, 'status': 'danger', 'index': None, 'pos': 'bottom-right'}
INFO 2017-12-06 18:43:39,061 core.notification.add: Adding notification to queue.
ERROR 2017-12-06 18:43:39,060 core.version._update_check: Current local hash not in git history.
DEBUG 2017-12-06 18:43:39,025 core.version.runner: Executing Git command: ['git', 'rev-list', '@{u}']
DEBUG 2017-12-06 18:43:39,025 core.version.get_commit_hash_history: Retreiving commit hash history.
INFO 2017-12-06 18:43:39,024 core.version._update_check: Current local hash: 3b0580452536dfa62cd730444e3774d7c64a29e4
DEBUG 2017-12-06 18:43:36,234 core.version.runner: Executing Git command: ['git', 'fetch']
DEBUG 2017-12-06 18:43:36,234 core.version.fetch: Fetching latest Git info.
DEBUG 2017-12-06 18:43:35,763 core.version.runner: Executing Git command: ['git', 'version']
DEBUG 2017-12-06 18:43:35,763 core.version.available: Checking Git execution permission.
INFO 2017-12-06 18:43:35,761 core.version.update_check: Checking for updates.
INFO 2017-12-06 18:43:35,759 CPTaskScheduler._task: == Executing Scheduled Task: Update Checker ==
```

**Comment by toogaz** [comment] 2017-12-08 09:18
Hello I've the same problem

**Comment by aldoinireland** [comment] 2017-12-09 11:43
same issue here

**Comment by MechEng70** [comment] 2017-12-13 03:27
ditto...

**Comment by nosmokingbandit** [comment] 2017-12-16 03:41
https://github.com/nosmokingbandit/Watcher3/issues/162

Duplicate of #162, so I'm closing this.

Either backup, re-clone, and restore or run the following commands:

```
  git fetch origin  
  git reset --hard origin/master
  git clean -f -d
```

**Closed by nosmokingbandit** 2017-12-16 03:41 UTC
