### ISSUE TITLE
latest update breaks watcher

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#237] opened 2018-04-02 01:30 UTC
```

INFO [2018-04-01 18:02:46,087] core.version.execute_update.209: Updating from Git.
INFO [2018-04-01 18:02:47,719] core.version.execute_update.225: Update successful.
INFO [2018-04-01 18:02:47,720] core.version.update_check.67: Update successful, restarting.
INFO [2018-04-01 18:02:47,720] cherrypy.error.error.219: [01/Apr/2018:18:02:47] ENGINE Bus STOPPING
INFO [2018-04-01 18:02:47,721] cherrypy.error.error.219: [01/Apr/2018:18:02:47] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
INFO [2018-04-01 18:02:47,722] cherrypy.error.error.219: [01/Apr/2018:18:02:47] ENGINE Stopped thread 'Session cleanup'.
INFO [2018-04-01 18:02:47,722] cherrypy.error.error.219: [01/Apr/2018:18:02:47] ENGINE Bus STOPPED
INFO [2018-04-01 18:02:47,722] core.restart.76: Server stopped -- respawning script as:
 /usr/local/bin/python /usr/local/Watcher3/watcher.py

```

```
Starting watcher.
Connected to database sqlite:////usr/local/Watcher3/userdata/watcher.sqlite
Database update required. This may take some time.
Backing up database to /usr/local/Watcher3/db.
Executing database update 7
Traceback (most recent call last):
  File "watcher.py", line 77, in <module>
    core.sql.update_database()
  File "/usr/local/Watcher3/core/sqldb.py", line 791, in update_database
    m()
  File "/usr/local/Watcher3/core/sqldb.py", line 964, in update_7
    if not i['imdbid'].startswith('tt'):
AttributeError: 'NoneType' object has no attribute 'startswith'
/usr/local/etc/rc.d/watcher: WARNING: failed to start watcher


```

**Comment by darrylmorley** [comment] 2018-04-02 11:38
Same issue here, I get the impression it's a timeout issue on a database upgrade?

Maybe adding a no timeout flag to the service file will help?

**Comment by darrylmorley** [comment] 2018-04-02 11:53
** Commit:4b0eb71
** Operating System: Debian 9
** Python Version [python -V]: python3
** What happened: Watcher doesn't start, timeout using systemctl.
** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
PASTE LOGS HERE
INFO [2018-04-02 12:24:37,873] CPTaskScheduler.stop.282: Stopping scheduled task Metadata Update.
INFO [2018-04-02 12:24:37,873] CPTaskScheduler.stop.282: Stopping scheduled task Update Checker.
INFO [2018-04-02 12:24:37,877] core.version.execute_update.209: Updating from Git.
INFO [2018-04-02 12:24:39,257] core.version.execute_update.225: Update successful.
INFO [2018-04-02 12:24:40,259] cherrypy.error.error.219: [02/Apr/2018:12:24:40] ENGINE Bus STOPPING
INFO [2018-04-02 12:24:40,265] cherrypy.error.error.219: [02/Apr/2018:12:24:40] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
INFO [2018-04-02 12:24:40,266] cherrypy.error.error.219: [02/Apr/2018:12:24:40] ENGINE Stopped thread 'Session cleanup'.
INFO [2018-04-02 12:24:40,267] cherrypy.error.error.219: [02/Apr/2018:12:24:40] ENGINE Bus STOPPED
INFO [2018-04-02 12:24:40,267] core.restart.76: Server stopped -- respawning script as: 
 /usr/bin/python3 /opt/watcher/watcher.py

**Comment by darrylmorley** [comment] 2018-04-02 11:57
Solved by setting no timeout in watcher.service.

**Comment by MaDTaZ** [comment] 2018-04-02 17:20
Hello All

I have added TimeoutSec=infinity and still errorring.
atcher.service - Watcher Daemon
   Loaded: loaded (/etc/systemd/system/watcher.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-04-02 10:11:52 PDT; 8min ago

Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]:     core.sql.update_database()
Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]:   File "/opt/watcher/watcher3/core/sqldb.py", line 791, in update_database
Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]:     m()
Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]:   File "/opt/watcher/watcher3/core/sqldb.py", line 964, in update_7
Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]:     if not i['imdbid'].startswith('tt'):
Apr 02 10:11:52 MaDTaZ-DarKNeT python3[32550]: AttributeError: 'NoneType' object has no attribute 'startswith'
Apr 02 10:11:52 MaDTaZ-DarKNeT systemd[1]: watcher.service: Control process exited, code=exited status=1
Apr 02 10:11:52 MaDTaZ-DarKNeT systemd[1]: Failed to start Watcher Daemon.
Apr 02 10:11:52 MaDTaZ-DarKNeT systemd[1]: watcher.service: Unit entered failed state.
Apr 02 10:11:52 MaDTaZ-DarKNeT systemd[1]: watcher.service: Failed with result 'exit-code'

**Comment by LeeThompson** [comment] 2018-04-02 17:29
The issue is actually because if imdbid does not have the tt prefix, Python sees it as a numeric value instead of a str.

```
Connected to database sqlite:///C:\Users\Public\Config\watcher\local\watcher.sql
ite
Database update required. This may take some time.
Backing up database to C:\Services\Watcher\Watcher3\db.
Executing database update 7
Traceback (most recent call last):
  File "watcher.py", line 77, in <module>
    core.sql.update_database()
  File "C:\Services\Watcher\Watcher3\core\sqldb.py", line 791, in update_databas
e
    m()
  File "C:\Services\Watcher\Watcher3\core\sqldb.py", line 964, in update_7
    if not i['imdbid'].startswith('tt'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The fix needs to be in `core/sqldb`

```
        for ind, i in enumerate(d):
            print('{}%\r'.format(int((ind + 1) / l * 100)), end='')
            t = str(i['imdbid'])
            if not t.startswith('tt'):
                n = 'tt' + t
                values.append({'imdbid': n, 'guid': i['guid']})
```

**Comment by LeeThompson** [comment] 2018-04-02 17:31
Also, if you are using --db or --userdata, it may try to put the backup database in the wrong place.

I would strongly suggest having a `core.DB_PATH` (constructed `fromcore.USERDATA`,` core.PROG_PATH` or derived from `passed_args.db `and then having `core\sqldb.py 773` read "`backup_dir = os.path.join(core.DB_PATH, 'db')`"

**Comment by nosmokingbandit** [comment] 2018-04-03 01:10
fd8279568095ce875fa4f3e5cec67e917f1bcd72 Should get everything running
normally as expected.

**Comment by LeeThompson** [comment] 2018-04-03 03:24
@nosmokingbandit Actually the if imdbid is missing the prefix, Python sees it as a numeric causing the .startswith to fail.   I still have the original database (I backed it up before I made my changes to sqldb to get running again).

I'm sure null is also a condition to check for a well.

**Comment by nosmokingbandit** [comment] 2018-04-03 03:40
If you would take the time to READ the exception it very clearly states `AttributeError: 'NoneType' object has no attribute 'startswith'`

None is NoneType. Integers are not Nonetype.

**Comment by LeeThompson** [comment] 2018-04-03 06:36
@nosmokingbandit I'll give you that, but the code above ran and got Watcher running again.    As a policy, the code should definitely also check for and handle nulls.    Python is not one of my main languages so I will defer to you.

**Comment by nosmokingbandit** [comment] 2018-04-06 23:41
If a null is expected it should be checked for, it would be irresponsible to check every value against null every time its type must be known. Why sqlalchemy returns None for an empty string is something that makes zero semantic sense.

Either way, this is fixed, so I'm closing.

**Closed by nosmokingbandit** 2018-04-06 23:41 UTC
